/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package airplane_ticket_reservaion_pearson; /* the command for the connection between the classes */

import java.sql.Connection; /*  it is used to bring certain classes or the entire packages, into visibility */
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Book_Ticket extends javax.swing.JInternalFrame {
/* 
    public = public is a Java keyword which declares a member's access as public.
    extends = indicates that a class is inherited from another class.
*/
    public Book_Ticket() {
        initComponents(); /* it is a method that swing Designer creates to initialise components */
        autoID(); /* TI0.. - call of a class that generates an ID for a ticket */
    }

    Connection con; /* used as a variable for the connection to the database */
    PreparedStatement pst; /* used to prepare for the functions of the database (insert,update...) */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Select_Country_Source = new javax.swing.JComboBox<>();
        Select_Country_Departure = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Ticket_ID_Book_Ticket = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Customer_ID_Book_Ticket = new javax.swing.JTextField();
        First_Name_Book_Ticket = new javax.swing.JLabel();
        Last_Name_Book_Ticket = new javax.swing.JLabel();
        Passport_ID_Book_Ticket = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Flight_ID_Book_Ticket = new javax.swing.JLabel();
        Flight_Name_Book_Ticket = new javax.swing.JLabel();
        Departure_Time_Book_Ticket = new javax.swing.JLabel();
        Class_Book_Ticket = new javax.swing.JComboBox<>();
        Base_Price_Book_Ticket = new javax.swing.JLabel();
        Seats_Book_Ticket = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        Final_Price_Book_Ticket = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 220));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Source");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Departure");

        Select_Country_Source.setBackground(new java.awt.Color(102, 102, 102));
        Select_Country_Source.setEditable(true);
        Select_Country_Source.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Select_Country_Source.setForeground(new java.awt.Color(255, 255, 255));
        Select_Country_Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birmingham", "Dothan", "Huntsville", "Mobile", "Montgomery" }));
        Select_Country_Source.setRequestFocusEnabled(false);

        Select_Country_Departure.setBackground(new java.awt.Color(102, 102, 102));
        Select_Country_Departure.setEditable(true);
        Select_Country_Departure.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Select_Country_Departure.setForeground(new java.awt.Color(255, 255, 255));
        Select_Country_Departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birmingham", "Dothan", "Huntsville", "Mobile", "Montgomery" }));
        Select_Country_Departure.setRequestFocusEnabled(false);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search For Available Flights");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Select_Country_Source, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Select_Country_Departure, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Select_Country_Departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_Country_Source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTable1.setBackground(java.awt.SystemColor.activeCaption);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Source", "Departure", "Date", "Departure Time", "Arrival Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ticket ID");

        Ticket_ID_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        Ticket_ID_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Ticket_ID_Book_Ticket.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passport ID");

        First_Name_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        First_Name_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        First_Name_Book_Ticket.setText("Not Selected");

        Last_Name_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Last_Name_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Last_Name_Book_Ticket.setText("Not Selected");

        Passport_ID_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Passport_ID_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Passport_ID_Book_Ticket.setText("Not Selected");

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Flight ID");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Flight Name");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Departure Time");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Class");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Base Price");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Seats");

        Flight_ID_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Flight_ID_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Flight_ID_Book_Ticket.setText("Not Selected");

        Flight_Name_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Flight_Name_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Flight_Name_Book_Ticket.setText("Not Selected");

        Departure_Time_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Departure_Time_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Departure_Time_Book_Ticket.setText("Not Selected");

        Class_Book_Ticket.setBackground(new java.awt.Color(102, 102, 102));
        Class_Book_Ticket.setEditable(true);
        Class_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Class_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Class_Book_Ticket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Businness" }));
        Class_Book_Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_Book_TicketActionPerformed(evt);
            }
        });

        Base_Price_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Base_Price_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Base_Price_Book_Ticket.setText("130");

        Seats_Book_Ticket.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Seats_Book_Ticket.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Seats_Book_Ticket.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seats_Book_TicketStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Final Price");

        Final_Price_Book_Ticket.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        Final_Price_Book_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Final_Price_Book_Ticket.setText("Not Selected");

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Book Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Ticket_ID_Book_Ticket))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Customer_ID_Book_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Name_Book_Ticket)
                    .addComponent(Last_Name_Book_Ticket)
                    .addComponent(jButton2)
                    .addComponent(Passport_ID_Book_Ticket))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(56, 56, 56)
                            .addComponent(Departure_Time_Book_Ticket))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Flight_Name_Book_Ticket))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(106, 106, 106)
                            .addComponent(Flight_ID_Book_Ticket)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Class_Book_Ticket, 0, 1, Short.MAX_VALUE)
                            .addComponent(Seats_Book_Ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(Base_Price_Book_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Final_Price_Book_Ticket)
                            .addComponent(jLabel22))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Customer_ID_Book_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(Flight_ID_Book_Ticket)
                            .addComponent(jLabel22))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Ticket_ID_Book_Ticket))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Final_Price_Book_Ticket)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(Flight_Name_Book_Ticket))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Departure_Time_Book_Ticket))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(First_Name_Book_Ticket)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton3)))
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Class_Book_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Last_Name_Book_Ticket))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Base_Price_Book_Ticket))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel8)
                    .addComponent(Passport_ID_Book_Ticket)
                    .addComponent(Seats_Book_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide(); /* closes the window */
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String Select_Source = Select_Country_Source.getSelectedItem().toString().trim();
        String Select_Depart = Select_Country_Departure.getSelectedItem().toString().trim();
        
        if(Select_Country_Source.getSelectedItem() == Select_Country_Departure.getSelectedItem()){
            JOptionPane.showMessageDialog(this, "Can't search for similar Departures and Sources...");  /* shows a message if the source and the departure are the same value */
        }
        else{
            try {
                Class.forName("com.mysql.jdbc.Driver"); /* it is a method that returns the class object associated with the class or interface passed as the first parameter */
                con = DriverManager.getConnection("jdbc:mysql://localhost/airplane_ticket_reservation","root",""); /* establishes connection to the local host */
                pst = con.prepareStatement("select * from flight where Source = ? and Departure = ?"); /* selects from the database */
                pst.setString(1, Select_Source); /* selects a value as a String and selects them with an order(the number is the order for the selection and the variable is what will be selected from the database) */
                pst.setString(2, Select_Depart);
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsm = rs.getMetaData();

                int c;
                c = rsm.getColumnCount(); /* the variable c is the numbers of the columns */

                DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                Df.setRowCount(0);

                while (rs.next()){ /* adds in every column it's data */
                    Vector v2 = new Vector();

                    for(int i = 1; i <= c;i++){
                        v2.add(rs.getString("ID"));
                        v2.add(rs.getString("Flight_Name"));
                        v2.add(rs.getString("Source"));
                        v2.add(rs.getString("Departure"));
                        v2.add(rs.getString("Date"));
                        v2.add(rs.getString("Departure_Time"));
                        v2.add(rs.getString("Arrival_Time"));
                    } 

                    Df.addRow(v2);                
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String Customer_ID_Book_T = Customer_ID_Book_Ticket.getText();
        
            try {
                Class.forName("com.mysql.jdbc.Driver"); /* it is a method that returns the class object associated with the class or interface passed as the first parameter */
                con = DriverManager.getConnection("jdbc:mysql://localhost/airplane_ticket_reservation","root",""); /* establishes connection to the local host */
                pst = con.prepareStatement("select * from customer where ID = ?"); /* selects from the database */
                pst.setString(1, Customer_ID_Book_T); /* selects a value as a String and selects them with an order(the number is the order for the selection and the variable is what will be selected from the database) */
                ResultSet rs = pst.executeQuery();

                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "Record not found"); /* shows a message if the customer id is not existent */
                }
                else{
                    String fname = rs.getString("First_Name");
                    String lname = rs.getString("Last_Name");                
                    String passport = rs.getString("Passport_ID");

                    First_Name_Book_Ticket.setText(fname.trim());
                    Last_Name_Book_Ticket.setText(lname.trim());                
                    Passport_ID_Book_Ticket.setText(passport.trim());

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel(); /* takes the information from the array and they are added to their corresponding position */
        
        int Select_Index = jTable1.getSelectedRow();
        
        Flight_ID_Book_Ticket.setText(Df.getValueAt(Select_Index, 0).toString()); /* Selects the right cell from the table and adds it to their corresponding position */
        Flight_Name_Book_Ticket.setText(Df.getValueAt(Select_Index, 1).toString());
        Departure_Time_Book_Ticket.setText(Df.getValueAt(Select_Index, 5).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void Class_Book_TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_Book_TicketActionPerformed
        // TODO add your handling code here:
        if (Class_Book_Ticket.getSelectedItem() == "Economy"){
            Base_Price_Book_Ticket.setText("130");
        }
        else{
            Base_Price_Book_Ticket.setText("250");
        }

    }//GEN-LAST:event_Class_Book_TicketActionPerformed

    private void Seats_Book_TicketStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seats_Book_TicketStateChanged
        // TODO add your handling code here:
        
        int Base_Price = Integer.parseInt(Base_Price_Book_Ticket.getText());
        int Quantity = Integer.parseInt(Seats_Book_Ticket.getValue().toString());
        
        int Final_Price = Base_Price * Quantity;
        
        Final_Price_Book_Ticket.setText(String.valueOf(Final_Price));        
        
    }//GEN-LAST:event_Seats_Book_TicketStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String Ticket_ID = Ticket_ID_Book_Ticket.getText();
        String Flight_ID = Flight_ID_Book_Ticket.getText();
        String Customer_ID = Customer_ID_Book_Ticket.getText();        
        String Flight_Class = Class_Book_Ticket.getSelectedItem().toString().trim();               
        String Final_Price = Final_Price_Book_Ticket.getText();
        String Seats = Seats_Book_Ticket.getValue().toString(); 
                         
            try {
                Class.forName("com.mysql.jdbc.Driver"); /* it is a method that returns the class object associated with the class or interface passed as the first parameter */
                con = DriverManager.getConnection("jdbc:mysql://localhost/airplane_ticket_reservation","root",""); /* establishes connection to the local host */
                pst = con.prepareStatement("insert into ticket(ID,Flight_ID,Customer_ID,Class,Price,Seats)values(?,?,?,?,?,?)"); /* inserts into the database */

                pst.setString(1, Ticket_ID); /* converts the values as a String and inputs them in an order in the database (the number is the order for the insert and the variable is what will be inserted into the database) */
                pst.setString(2, Flight_ID);
                pst.setString(3, Customer_ID);
                pst.setString(4, Flight_Class);
                pst.setString(5, Final_Price);
                pst.setString(6, Seats);           

                pst.executeUpdate(); /* database update */

                JOptionPane.showMessageDialog(null, "Ticket booked...");  /* confirmation message for the data insertion in the database */
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Add_Flight.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Add_Flight.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void autoID(){
        try {
            Class.forName("com.mysql.jdbc.Driver"); /* it is a method that returns the class object associated with the class or interface passed as the first parameter */
            con = DriverManager.getConnection("jdbc:mysql://localhost/airplane_ticket_reservation","root","");  /* establishes connection to the local host */
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(id) from ticket"); /* searches the max ID in the database for the ticket */
            rs.next();
            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null){
                Ticket_ID_Book_Ticket.setText("TI001");
            }
            else{
                long id = Long.parseLong(rs.getString("MAX(id)").substring(2,rs.getString("MAX(id)").length()));
                id++;
                Ticket_ID_Book_Ticket.setText("TI" + String.format("%03d", id));
                
            } 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Base_Price_Book_Ticket;
    private javax.swing.JComboBox<String> Class_Book_Ticket;
    private javax.swing.JTextField Customer_ID_Book_Ticket;
    private javax.swing.JLabel Departure_Time_Book_Ticket;
    private javax.swing.JLabel Final_Price_Book_Ticket;
    private javax.swing.JLabel First_Name_Book_Ticket;
    private javax.swing.JLabel Flight_ID_Book_Ticket;
    private javax.swing.JLabel Flight_Name_Book_Ticket;
    private javax.swing.JLabel Last_Name_Book_Ticket;
    private javax.swing.JLabel Passport_ID_Book_Ticket;
    private javax.swing.JSpinner Seats_Book_Ticket;
    private javax.swing.JComboBox<String> Select_Country_Departure;
    private javax.swing.JComboBox<String> Select_Country_Source;
    private javax.swing.JLabel Ticket_ID_Book_Ticket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
