/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package airplane_ticket_reservaion_pearson; /* the command for the connection between the classes */

import java.sql.Connection; /*  it is used to bring certain classes or the entire packages, into visibility */
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Ticket_Report extends javax.swing.JInternalFrame {
/* 
    public = public is a Java keyword which declares a member's access as public.
    extends = indicates that a class is inherited from another class.
*/
    public Ticket_Report() {
        initComponents(); /* it is a method that swing Designer creates to initialise components */
        Load_Tickets(); /* calss a class */
    }
    
    Connection con; /* used as a variable for the connection to the database */
    PreparedStatement pst; /* used to prepare for the functions of the database (insert,update...) */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Flight_ID", "Customer_ID", "Class", "Price", "Seats"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide(); /* closes the window */
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Load_Tickets(){
    
        try {
            Class.forName("com.mysql.jdbc.Driver"); /* it is a method that returns the class object associated with the class or interface passed as the first parameter */
            con = DriverManager.getConnection("jdbc:mysql://localhost/airplane_ticket_reservation","root",""); /* establishes connection to the local host */
            pst = con.prepareStatement("select * from ticket"); /* selects from database */
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsm = rs.getMetaData();            
            int c;
            c = rsm.getColumnCount(); /* the variable c is the numbers of the columns */
            
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            
            while (rs.next()){ /* adds in every column it's data */
                Vector v2 = new Vector();
                
                for(int i = 1; i <= c;i++){
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("Flight_ID"));
                    v2.add(rs.getString("Customer_ID"));
                    v2.add(rs.getString("Class"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("Seats"));                    
                } 
                
                Df.addRow(v2);                
            }
               
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ticket_Report.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ticket_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
